services:
  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379
    restart: always
  app-a:
    container_name: app-a
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    restart: always
    environment:
      REDIS_URL: redis:6379
    volumes:
      - ../:/app
  app-b:
    container_name: app-b
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    restart: always
    environment:
      REDIS_URL: redis:6379
    volumes:
      - ../:/app
